version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=ct313h_labs
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql